<?php

// File Generated by Numinix Product Fields
// @package admin
// @copyright Copyright 2003-2013 Zen Cart Development Team
// @copyright Portions Copyright 2003 osCommerce
// @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
// 
if (!defined('IS_ADMIN_FLAG')) {
  die('Illegal Access');
}

if (isset($_POST['exclude_from_google_feed'])) {
  $sql_data_array['exclude_from_google_feed'] = zen_db_prepare_input($_POST['exclude_from_google_feed']);
} else {
  $sql_data_array['exclude_from_google_feed'] = '0';
}
$pInfo->exclude_from_google_feed = $sql_data_array['exclude_from_google_feed'];
