<?php
/**
 * Numinix Product Fields - Override File Generator
 * 
 * This utility generates Zen Cart v2 override files for NPF integration.
 * It reads the base Zen Cart files and applies NPF modifications automatically.
 * 
 * @copyright Copyright 2024 Numinix
 * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0
 * @version 4.1.0
 * 
 * USAGE:
 * 1. Upload this file to YOUR_ADMIN directory
 * 2. Access it via browser: http://yourstore.com/YOUR_ADMIN/npf_generate_overrides.php
 * 3. Click "Generate Override Files"
 * 4. Review the generated files
 * 5. Delete this generator script after use
 */

// Security check
define('IS_ADMIN_FLAG', true);
require('includes/application_top.php');

if (!isset($_SESSION['admin_id']) || !zen_is_superuser()) {
    die('Access denied. You must be logged in as a superuser to use this tool.');
}

$output = [];
$success = true;

// Define the override directory
$override_dir = DIR_FS_ADMIN . 'includes/modules/product/';

if (!file_exists($override_dir)) {
    mkdir($override_dir, 0755, true);
    $output[] = "Created directory: $override_dir";
}

/**
 * Generate collect_info.php override
 */
function generate_collect_info_override() {
    global $output, $override_dir;
    
    $base_file = DIR_FS_ADMIN . 'includes/modules/collect_info.php';
    $override_file = $override_dir . 'collect_info.php';
    
    if (!file_exists($base_file)) {
        $output[] = "ERROR: Base file not found: $base_file";
        return false;
    }
    
    $content = file_get_contents($base_file);
    
    // Find the location to insert NPF SQL include (after the security check)
    $npf_sql_include = "\n// ===== NPF MODIFICATION START =====\n" .
                      "// NPF: Load SQL extensions for additional custom fields\n" .
                      "if (file_exists(DIR_WS_INCLUDES . 'npf_includes/npf_collect_info_sql.php')) {\n" .
                      "    include(DIR_WS_INCLUDES . 'npf_includes/npf_collect_info_sql.php');\n" .
                      "}\n" .
                      "// ===== NPF MODIFICATION END =====\n\n";
    
    // Insert after the security check
    $content = str_replace(
        "}\n\n\$parameters = [",
        "}\n" . $npf_sql_include . "\$parameters = [",
        $content
    );
    
    // Modify the SQL query to include NPF fields
    $old_query = "date_format(p.products_date_available, '\" .  zen_datepicker_format_forsql() . \"') as products_date_available\n" .
                "                           FROM \" . TABLE_PRODUCTS . \" p\n" .
                "                           LEFT JOIN \" . TABLE_PRODUCTS_DESCRIPTION . \" pd ON (p.products_id = pd.products_id AND pd.language_id = \" . (int)\$_SESSION['languages_id'] . \")\n" .
                "                           WHERE p.products_id = \"";
    
    $new_query = "date_format(p.products_date_available, '\" .  zen_datepicker_format_forsql() . \"') as products_date_available\" . \n" .
                "                                  (isset(\$npf_fields) ? \$npf_fields : '') . \"\n" .
                "                           FROM \" . TABLE_PRODUCTS . \" p\n" .
                "                           LEFT JOIN \" . TABLE_PRODUCTS_DESCRIPTION . \" pd ON (p.products_id = pd.products_id AND pd.language_id = \" . (int)\$_SESSION['languages_id'] . \")\" .\n" .
                "                           (isset(\$npf_tables) ? \$npf_tables : '') . \"\n" .
                "                           WHERE p.products_id = \"";
    
    $content = str_replace($old_query, $new_query, $content);
    
    // Add NPF header comments
    $header = "<?php\n" .
             "/**\n" .
             " * Numinix Product Fields - Override for collect_info.php\n" .
             " * \n" .
             " * AUTO-GENERATED FILE - Do not edit manually!\n" .
             " * Generated by: npf_generate_overrides.php\n" .
             " * Generated on: " . date('Y-m-d H:i:s') . "\n" .
             " * \n" .
             " * This file contains NPF modifications to load custom field data.\n" .
             " * It automatically overrides the base collect_info.php file.\n" .
             " * \n" .
             " * @copyright Copyright 2003-2025 Zen Cart Development Team\n" .
             " * @copyright Copyright 2024 Numinix\n" .
             " * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0\n" .
             " */\n";
    
    $content = preg_replace('/<\?php.*?\*\//s', $header, $content, 1);
    
    // Write the override file
    if (file_put_contents($override_file, $content)) {
        $output[] = "✓ Generated: collect_info.php";
        return true;
    } else {
        $output[] = "ERROR: Could not write file: $override_file";
        return false;
    }
}

/**
 * Generate update_product.php override
 */
function generate_update_product_override() {
    global $output, $override_dir;
    
    $base_file = DIR_FS_ADMIN . 'includes/modules/update_product.php';
    $override_file = $override_dir . 'update_product.php';
    
    if (!file_exists($base_file)) {
        $output[] = "ERROR: Base file not found: $base_file";
        return false;
    }
    
    $content = file_get_contents($base_file);
    
    // Modification 1: After $sql_data_array is created
    $npf_include_1 = "\n  // NPF: Include SQL array builder for products table\n" .
                    "  if (file_exists(DIR_WS_INCLUDES . 'npf_includes/npf_update_product_sql.php')) {\n" .
                    "      include(DIR_WS_INCLUDES . 'npf_includes/npf_update_product_sql.php');\n" .
                    "  }\n\n";
    
    // Find where to insert (typically after the closing of $sql_data_array)
    $content = preg_replace(
        '/(\);)\s*\n\s*\n\s*(\$db_filename = )/s',
        "$1" . $npf_include_1 . "  $2",
        $content,
        1
    );
    
    // Modification 2: In products_description loop
    $npf_include_2 = "\n      // NPF: Include SQL array builder for products_description table\n" .
                    "      if (file_exists(DIR_WS_INCLUDES . 'npf_includes/npf_update_product_description_sql.php')) {\n" .
                    "          include(DIR_WS_INCLUDES . 'npf_includes/npf_update_product_description_sql.php');\n" .
                    "      }\n\n";
    
    $content = preg_replace(
        "/(\'products_url\' => zen_db_prepare_input\(\\\$_POST\[\'products_url\'\]\[\\\$language_id\]\)\);)\s*\n\s*\n\s*(if \(\\\$action == \'insert_product\'\))/s",
        "$1" . $npf_include_2 . "    $2",
        $content,
        1
    );
    
    // Modification 3: Before final redirect
    $npf_include_3 = "\n    // NPF: Execute custom scripts after product data is saved\n" .
                    "    if (file_exists(DIR_WS_INCLUDES . 'npf_includes/npf_custom_execute.php')) {\n" .
                    "        include(DIR_WS_INCLUDES . 'npf_includes/npf_custom_execute.php');\n" .
                    "    }\n\n";
    
    $content = preg_replace(
        '/(\}\s*\n\s*\n)(\s*\$zco_notifier->notify\(\'NOTIFY_MODULES_UPDATE_PRODUCT_END\')/s',
        "$1" . $npf_include_3 . "$2",
        $content,
        1
    );
    
    // Add NPF header comments
    $header = "<?php\n" .
             "/**\n" .
             " * Numinix Product Fields - Override for update_product.php\n" .
             " * \n" .
             " * AUTO-GENERATED FILE - Do not edit manually!\n" .
             " * Generated by: npf_generate_overrides.php\n" .
             " * Generated on: " . date('Y-m-d H:i:s') . "\n" .
             " * \n" .
             " * This file contains NPF modifications to save custom field data.\n" .
             " * It automatically overrides the base update_product.php file.\n" .
             " * \n" .
             " * @copyright Copyright 2003-2025 Zen Cart Development Team\n" .
             " * @copyright Copyright 2024 Numinix\n" .
             " * @license http://www.zen-cart.com/license/2_0.txt GNU Public License V2.0\n" .
             " */\n";
    
    $content = preg_replace('/<\?php.*?\*\//s', $header, $content, 1);
    
    // Write the override file
    if (file_put_contents($override_file, $content)) {
        $output[] = "✓ Generated: update_product.php";
        return true;
    } else {
        $output[] = "ERROR: Could not write file: $override_file";
        return false;
    }
}

// Process form submission
if (isset($_POST['generate'])) {
    $success = generate_collect_info_override() && generate_update_product_override();
    
    if ($success) {
        $output[] = "\n✓ SUCCESS! Override files have been generated successfully.";
        $output[] = "\nNext steps:";
        $output[] = "1. Test your product edit pages to ensure NPF fields display correctly";
        $output[] = "2. Test creating and updating products";
        $output[] = "3. Delete this generator script (npf_generate_overrides.php) for security";
    } else {
        $output[] = "\n✗ FAILED! Some files could not be generated. Check the errors above.";
    }
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>NPF Override File Generator</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            border-bottom: 2px solid #0066cc;
            padding-bottom: 10px;
        }
        .info {
            background-color: #e7f3ff;
            border-left: 4px solid #0066cc;
            padding: 15px;
            margin: 20px 0;
        }
        .warning {
            background-color: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
        }
        .output {
            background-color: #f8f9fa;
            border: 1px solid #dee2e6;
            padding: 15px;
            margin: 20px 0;
            font-family: monospace;
            white-space: pre-wrap;
            max-height: 400px;
            overflow-y: auto;
        }
        .success {
            color: #28a745;
        }
        .error {
            color: #dc3545;
        }
        button {
            background-color: #0066cc;
            color: white;
            border: none;
            padding: 12px 24px;
            font-size: 16px;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background-color: #0052a3;
        }
        button:disabled {
            background-color: #ccc;
            cursor: not-allowed;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Numinix Product Fields - Override File Generator</h1>
        
        <div class="info">
            <strong>What does this do?</strong><br>
            This utility automatically generates Zen Cart v2 override files for NPF integration.
            Instead of manually editing core Zen Cart files, it creates override versions in the
            <code>/product/</code> subdirectory that Zen Cart automatically uses.
        </div>
        
        <div class="warning">
            <strong>⚠ Important:</strong><br>
            • This will create/overwrite files in: <code><?php echo $override_dir; ?></code><br>
            • Make sure you have backups of your site before proceeding<br>
            • Delete this generator script after use for security
        </div>
        
        <?php if (!empty($output)): ?>
        <div class="output <?php echo $success ? 'success' : 'error'; ?>">
<?php echo htmlspecialchars(implode("\n", $output)); ?>
        </div>
        <?php endif; ?>
        
        <form method="post">
            <button type="submit" name="generate" <?php echo isset($_POST['generate']) && $success ? 'disabled' : ''; ?>>
                <?php echo isset($_POST['generate']) && $success ? '✓ Files Generated' : 'Generate Override Files'; ?>
            </button>
        </form>
        
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666;">
            Numinix Product Fields v4.1 | Generator Script | Delete after use
        </div>
    </div>
</body>
</html>
